cmake_minimum_required(VERSION 3.15)
project(runner LANGUAGES CXX)
set(BINARY_NAME "warp_vpn_app")
set(APPLICATION_ID "com.example.warp_vpn_app")
find_package(flutter REQUIRED)
add_executable(${BINARY_NAME} WIN32 main.cpp flutter_window.cpp win32_window.cpp run_loop.cpp utils.cpp ${BINARY_NAME}.rc)
target_compile_definitions(${BINARY_NAME} PRIVATE APPLICATION_ID="${APPLICATION_ID}")
target_include_directories(${BINARY_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(${BINARY_NAME} flutter flutter_wrapper_app)
target_include_directories(${BINARY_NAME} PRIVATE ${flutter_INCLUDE_DIRS})
target_compile_definitions(${BINARY_NAME} PRIVATE UNICODE _UNICODE)
target_compile_features(${BINARY_NAME} PRIVATE cxx_std_17)
add_custom_command(TARGET ${BINARY_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different "${FLUTTER_LIBRARY}" "$<TARGET_FILE_DIR:${BINARY_NAME}>" COMMAND ${CMAKE_COMMAND} -E copy_if_different "${FLUTTER_WRAPPER_LIBRARY}" "$<TARGET_FILE_DIR:${BINARY_NAME}>" COMMAND ${CMAKE_COMMAND} -E copy_if_different "${flutter_TOOLCHAIN_DIR}/icudtl.dat" "$<TARGET_FILE_DIR:${BINARY_NAME}>")
